from naive_reporter.config import settings

# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

SYNTHETIC_QUERY_PROMPT = (
    f"You are given a user request. Generate exactly "
    f"{settings.number_of_synthetic_user_queries} search queries "
    "(one per line, no numbering) that would help find documents relevant to "
    "this request.\n"
    "\n"
    "User request:\n"
    "---\n"
    "{prompt}\n"
    "---\n"
    "\n"
    "Search queries:\n"
)

REPORT_GENERATION_PROMPT = (
    "You are a research analyst. Write a detailed report that answers the "
    "user's request based solely on the provided documents. You must not use "
    "any outside knowledge, assumptions, or information not explicitly "
    "present in the documents. If the documents do not contain enough "
    "information to answer part of the request, state that explicitly.\n"
    "\n"
    "User request:\n"
    "---\n"
    "{prompt}\n"
    "---\n"
    "\n"
    "Documents:\n"
    "{documents}\n"
    "\n"
    "Report:\n"
)

REPORT_RETRY_PROMPT = (
    "You are a research analyst. A previous version of this report was "
    "rejected by a reviewer. You must now produce a corrected report that "
    "addresses the feedback. Use only the provided documents — no outside "
    "knowledge.\n"
    "\n"
    "User request:\n"
    "---\n"
    "{prompt}\n"
    "---\n"
    "\n"
    "Documents:\n"
    "{documents}\n"
    "---\n"
    "\n"
    "Your previous report:\n"
    "---\n"
    "{previous_report}\n"
    "---\n"
    "\n"
    "Reviewer's feedback:\n"
    "---\n"
    "{feedback}\n"
    "---\n"
    "\n"
    "Please write a corrected report that fully addresses the feedback.\n"
    "\n"
    "Corrected report:\n"
)

REPORT_VALIDATION_PROMPT = (
    "You are a critical reviewer. Determine whether the report is true, "
    "fulfills the user's request, and uses ONLY knowledge from the provided "
    "documents with no outside information or hallucination. Respond with "
    "exactly: VALID or INVALID:<reason>\n"
    "\n"
    "User request:\n"
    "---\n"
    "{prompt}\n"
    "---\n"
    "\n"
    "Documents:\n"
    "{documents}\n"
    "\n"
    "Report:\n"
    "---\n"
    "{report}\n"
    "---\n"
    "\n"
    "Your verdict:\n"
)

BULLET_GENERATION_PROMPT = (
    "Summarize this report into at most 3 bullet points. Each bullet point "
    "must be at most 2 sentences and as concise as possible.\n"
    "\n"
    "Report:\n"
    "---\n"
    "{report}\n"
    "---\n"
    "\n"
    "Bullet points:\n"
)

BULLET_RETRY_PROMPT = (
    "You are an editor. A previous version of this bullet summary was "
    "rejected by a reviewer. Produce a corrected bullet summary that "
    "fully addresses the feedback. Keep at most 3 bullet points, "
    "each at most 2 sentences.\n"
    "\n"
    "Report:\n"
    "---\n"
    "{report}\n"
    "---\n"
    "\n"
    "Your previous bullet summary:\n"
    "---\n"
    "{previous_bullets}\n"
    "---\n"
    "\n"
    "Reviewer's feedback:\n"
    "---\n"
    "{feedback}\n"
    "---\n"
    "\n"
    "Please write a corrected bullet summary.\n"
    "\n"
    "Corrected bullet points:\n"
)

BULLET_VALIDATION_PROMPT = (
    "You are a critical reviewer. Determine whether this bullet summary "
    "accurately captures the key points of the report and follows the "
    "constraint of at most 3 bullets with at most 2 sentences each. Respond "
    "with exactly: VALID or INVALID:<reason>\n"
    "\n"
    "Report:\n"
    "---\n"
    "{report}\n"
    "---\n"
    "\n"
    "Bullet summary:\n"
    "---\n"
    "{bullets}\n"
    "---\n"
    "\n"
    "Your verdict:\n"
)
